modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="trickortreatpixelmon"
version="1.2.0-pixelmon"
displayName="Halloween Trick or Treat Pixelmon"
description='''
Halloween-themed trick or treat mod for Pixelmon servers with custom skyblock rewards.
'''
authors="Halloween Team"
credits="Pixelmon Reforged Team"

[[dependencies.trickortreatpixelmon]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.trickortreatpixelmon]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"

[[dependencies.trickortreatpixelmon]]
modId="pixelmon"
mandatory=true
versionRange="[9.1.11]"
ordering="NONE"
side="BOTH"
