modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="trickortreatpixelmon"
version="0.0.1"
displayName="Mod name"
displayURL="https://github.com/EnvyWare" # URL HERE
credits="https://github.com/EnvyWare" # Your name here
authors="https://github.com/EnvyWare" # Your name here
description='''
Description of the mod here
'''

[[dependencies.trickortreatpixelmon]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.trickortreatpixelmon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"


[[dependencies.trickortreatpixelmon]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.2,)"
    ordering="NONE"
    side="BOTH"